const skillNodes = [
  { id: 'programming', label: 'Programming', level: 9, knowledge: 9, experience: 8, effect: 'Unlocks all programming skills', utilizedIn: ['All Systems Developed'] },
  { id: 'frontend', label: 'Frontend', level: 4, knowledge: 4, experience: 4, effect: 'Unlocks frontend development skills', utilizedIn: ['Portfolio website'] },
  { id: 'backend', label: 'Backend', level: 7, knowledge: 7, experience: 5, effect: 'Unlocks backend development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System'] },
  { id: 'react', label: 'React', level: 4, knowledge: 2, experience: 3, effect: 'Unlocks React development skills', utilizedIn: ['Portfolio website'] },
  { id: 'css', label: 'CSS', level: 6, knowledge: 5, experience: 5, effect: 'Unlocks CSS styling skills', utilizedIn: ['Portfolio website', 'Hydroponic System'] },
  { id: 'node', label: 'Node.js', level: 1, knowledge: 1, experience: 0, effect: 'Unlocks Node.js development skills', utilizedIn: ['Practice Systems'] },
  { id: 'db', label: 'Databases', level: 6, knowledge: 6, experience: 6, effect: 'Unlocks database management skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System'] },
  { id: 'php', label: 'PHP', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks PHP development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System'] },
  { id: 'phython', label: 'Python', level: 6, knowledge: 4, experience: 5, effect: 'Unlocks Python development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System'] },
  { id: 'flask', label: 'Flask', level: 5, knowledge: 3, experience: 5, effect: 'Unlocks Flask development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System'] },
  { id: 'C#', label: 'C#', level: 5, knowledge: 5, experience: 3, effect: 'Unlocks C# development skills', utilizedIn: ['School Projects during College'] },
  { id: 'bootstrap', label: 'Bootstrap', level: 7, knowledge: 6, experience: 7, effect: 'Unlocks Bootstrap development skills', utilizedIn: ['Hydroponic System', 'Portfolio website'] },
  { id: 'godot', label: 'Godot', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks Godot development skills', utilizedIn: ['Elemental Survivors'] },
  { id: 'game_dev', label: 'Game Development', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks Game development skills', utilizedIn: ['Elemental Survivors'] },
  { id: 'gdscript', label: 'GDScript', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks GDScript development skills', utilizedIn: ['Elemental Survivors'] },
  { id: 'sprite', label: 'Sprite Animation', level: 6, knowledge: 7, experience: 4, effect: 'Unlocks Sprite animation skills', utilizedIn: ['Elemental Survivors', 'Portfolio website'] },
  { id: 'aseprite', label: 'Aseprite', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks Aseprite development skills', utilizedIn: ['Elemental Survivors', 'Portfolio website'] },
  { id: 'sound', label: 'Sound Design', level: 6, knowledge: 6, experience: 4, effect: 'Unlocks Sound design skills', utilizedIn: ['Elemental Survivors'] },
  { id: 'bgm', label: 'FL Studio', level: 4, knowledge: 3, experience: 3, effect: 'Unlocks Sound design skills', utilizedIn: ['Elemental Survivors'] },
  { id: 'web-dev', label: 'Web Development', level: 8, knowledge: 7, experience: 6, effect: 'Unlocks web development skills', utilizedIn: ['Portfolio website', 'Hydroponic System', 'School Schedule Conflict Resolution System'] },
  { id: 'api', label: 'API Development', level: 6, knowledge: 5, experience: 4, effect: 'Unlocks API development skills', utilizedIn: ['Hydroponic System', 'School Schedule Conflict Resolution System'] },
  { id: 'asp', label: 'ASP.NET', level: 7, knowledge: 6, experience: 5, effect: 'Unlocks ASP.NET development skills', utilizedIn: ['School Projects during College'] },
  { id: 'laravel', label: 'Laravel', level: 6, knowledge: 4, experience: 3, effect: 'Unlocks Laravel development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Practice Systems'] },
  { id: 'sql', label: 'MySQL', level: 6, knowledge: 5, experience: 5, effect: 'Unlocks SQL development skills', utilizedIn: ['School Schedule Conflict Resolution System', 'Hydroponic System', 'Practice Systems', 'API Development', 'School Projects during College'] },
  { id: 'js', label: 'JavaScript', level: 5, knowledge: 4, experience: 4, effect: 'Unlocks JavaScript development skills', utilizedIn: ['Portfolio website', 'Hydroponic System', 'School Schedule Conflict Resolution System'] },
  { id: 'tool', label: 'Tools', level: 7, knowledge: 6, experience: 5, effect: 'Unlocks tool usage skills', utilizedIn: ['Portfolio website', 'Hydroponic System', 'School Schedule Conflict Resolution System', 'API Development'] },
  { id: 'git', label: 'Git', level: 6, knowledge: 5, experience: 5, effect: 'Unlocks Git development skills', utilizedIn: ['Portfolio website', 'Hydroponic System', 'School Schedule Conflict Resolution System'] },
];

export default skillNodes;
